name: Deploy React to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install
        run: npm install

      # 4. Build project
      - name: Build
        run: npm run build

      # 5. Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.87.227.86 >> ~/.ssh/known_hosts

      # 6. Deploy
      - name: Deploy
        run: |
          scp -i ~/.ssh/id_rsa -r dist/* ec2-user@54.87.227.86:/tmp/

          ssh -i ~/.ssh/id_rsa ec2-user@54.87.227.86 << 'EOF'
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r /tmp/* /usr/share/nginx/html/
            sudo systemctl restart nginx
          EOF