name: Deploy React App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r dist/* ec2-user@54.87.227.86:/tmp/

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@54.87.227.86 << 'EOF'
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r /tmp/* /usr/share/nginx/html/
          EOF